# SUMMARY:
#
# Build and push an image using Docker Buildkit.
#
# USAGE:
#
# Publishing images requires an access token. For hub.docker.com you can create one at https://hub.docker.com/settings/security
# This needs to be mounted as `$DOCKER_CONFIG/config.json`. To do this, you'll need to create a secret as follows:
#
#    export DOCKER_USERNAME=******
#    export DOCKER_TOKEN=******
#    kubectl create secret generic docker-config --from-literal="config.json={\"auths\": {\"https://index.docker.io/v1/\": {\"auth\": \"$(echo -n $DOCKER_USERNAME:$DOCKER_TOKEN|base64)\"}}}"
#
# REFERENCES:
#
# * https://github.com/moby/buildkit#expose-buildkit-as-a-tcp-service
# * https://blog.alexellis.io/building-containers-without-docker/
# * https://hub.docker.com/r/moby/buildkit
#
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: docker-build-push
  namespace: argo
  labels:
spec:
  templates:
    - name: main
      inputs: {}
      outputs: {}
      metadata: {}
      dag:
        tasks:
          - name: clone
            template: clone
            arguments:
              parameters:
                - name: repo
                  value: '{{workflow.parameters.repo}}'
                - name: branch
                  value: '{{workflow.parameters.branch}}'
          - name: image
            template: image
            arguments:
              parameters:
                - name: path
                  value: '{{workflow.parameters.path}}'
                - name: image
                  value: '{{workflow.parameters.image}}'
                - name: account
                  value: '{{workflow.parameters.account}}'
                - name: tag
                  value: '{{workflow.parameters.tag}}'
            depends: clone
    - name: clone
      inputs:
        parameters:
          - name: repo
          - name: branch
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'alpine/git:v2.26.2'
        command:
          - git
        args:
          - clone
          - '{{inputs.parameters.repo}}'
          - .
        workingDir: /work
        resources: {}
        volumeMounts:
          - name: work
            mountPath: /work
    - name: image
      inputs:
        parameters:
          - name: path
          - name: image
          - name: tag
          - name: account
      outputs: {}
      metadata: {}
      container:
        name: ''
        image: 'moby/buildkit:v0.9.3-rootless'
        command:
          - buildctl-daemonless.sh
        args:
          - build
          - '--frontend'
          - dockerfile.v0
          - '--local'
          - context=.
          - '--local'
          - dockerfile=.
          - '--output'
          - >-
            type=image,name=docker.io/{{inputs.parameters.account}}/{{inputs.parameters.image}}:{{inputs.parameters.tag}},push=true
        workingDir: '/work/{{inputs.parameters.path}}'
        env:
          - name: BUILDKITD_FLAGS
            value: '--oci-worker-no-process-sandbox'
          - name: DOCKER_CONFIG
            value: /.docker
        resources: {}
        volumeMounts:
          - name: work
            mountPath: /work
          - name: docker-config
            mountPath: /.docker
        securityContext:
          privileged: true
      volumes:
        - name: docker-config
          secret:
            secretName: docker-config
  entrypoint: main
  arguments:
    parameters:
      - name: repo
        value: 'https://github.com/nabhanxyz/argo-terraform'
      - name: branch
        value: main
      - name: path
        value: /
      - name: account
        value: mikenabhan
      - name: image
        value: argo-terraform
      - name: tag
        value: dev
  volumeClaimTemplates:
    - metadata:
        name: work
        creationTimestamp: null
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 64Mi
      status: {}
